name: front-linter

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: ESLint
        run: npm run fix .
        working-directory: ./server

      - name: Prettier
        run: npm run fix:prettier
        working-directory: ./server