name: Front-end Linter

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' 
          cache-dependency-path: 'server/package-lock.json'

      - name: Install dependencies
        run: npm ci 
        working-directory: ./server
        
      - name: Run ESLint Check
        run: npm run lint # Asegúrate de tener un script "lint" en tu package.json
        working-directory: ./server

      - name: Run Prettier Check
        run: npm run prettier:check # O el comando que uses para verificar con Prettier
        working-directory: ./server